### ISSUE TITLE
run rspec need to add bundle exec

### ISSUE THREAD

**Issue by wendy0402** [ArturT/knapsack#31]
when I use knapsack with rspec. When try to run it with command `rspec`, it give errors:
```
/Users/fakeuser/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.14.1/lib/active_support/dependencies.rb:247:in `require': cannot load such file -- knapsack (LoadError)
	from /Users/fakeuser/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.14.1/lib/active_support/dependencies.rb:247:in `block in require'
	from /Users/fakeuser/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.14.1/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /Users/fakeuser/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.14.1/lib/active_support/dependencies.rb:247:in `require'
	from /Users/fakeuser/Sites/turbo/spec/spec_helper.rb:4:in `<top (required)>'
	from /Users/fakeuser/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.14.1/lib/active_support/dependencies.rb:247:in `require'
	from /Users/fakeuser/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.14.1/lib/active_support/dependencies.rb:247:in `block in require'
	from /Users/fakeuser/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.14.1/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /Users/fakeuser/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.14.1/lib/active_support/dependencies.rb:247:in `require'
	from /Users/fakeuser/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1280:in `block in requires='
	from /Users/fakeuser/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1280:in `each'
	from /Users/fakeuser/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1280:in `requires='
	from /Users/fakeuser/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/configuration_options.rb:109:in `block in process_options_into'
	from /Users/fakeuser/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/configuration_options.rb:108:in `each'
	from /Users/fakeuser/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/configuration_options.rb:108:in `process_options_into'
	from /Users/fakeuser/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/configuration_options.rb:21:in `configure'
	from /Users/fakeuser/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:101:in `setup'
	from /Users/fakeuser/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:88:in `run'
	from /Users/fakeuser/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:73:in `run'
	from /Users/fakeuser/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:41:in `invoke'
	from /Users/fakeuser/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/exe/rspec:4:in `<top (required)>'
	from /Users/fakeuser/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.14.1/lib/active_support/dependencies.rb:241:in `load'
	from /Users/fakeuser/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.14.1/lib/active_support/dependencies.rb:241:in `block in load'
	from /Users/fakeuser/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.14.1/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /Users/fakeuser/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.14.1/lib/active_support/dependencies.rb:241:in `load'
	from /Users/fakeuser/.rvm/gems/ruby-2.1.5/gems/spring-commands-rspec-1.0.4/lib/spring/commands/rspec.rb:18:in `call'
	from /Users/fakeuser/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/fakeuser/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

but when run it with `bundle exec rspec`, it works like a charm.
have anyone know the reason?

**Comment by ArturT** [comment]
Hi @wendy0402 
This is a common problem. bundle exec rspec executes in the context of your bundle so you should use it instead of just rspec. Take a look http://stackoverflow.com/a/8275912/905697
