### ISSUE TITLE
Rspec callbacks are not called

### ISSUE THREAD

**Issue by radubogdan** [ArturT/knapsack#56]
Hey guys,

I'm trying to use knapsack and semaphoreapp CI to spread the tests across multiple nodes and it looks like the `before :each` callback from `spec_helper.rb` is not running before the specs.

**localhost**

```
knapsack rspec                                                                                                       ✹chore/knapsack-split-specs ‹2.4.0›

Report specs:
[SOME IRRELEVANT SPEC PATHS]

Leftover specs:
[SOME IRRELEVANT SPEC PATHS]

Knapsack time offset warning enabled!

################## Rspec configure

bundler: failed to load command: rspec (/Users/raducroitoru/.rbenv/versions/2.4.0/bin/rspec)
CountryManager::CountryNotSet: The country_code is not set!
  /Users/raducroitoru/Coding/Work/A/a/lib/country_manager.rb:88:in `block in country'
  /Users/raducroitoru/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/request_store-1.3.2/lib/request_store.rb:47:in `fetch'
  /Users/raducroitoru/Coding/Work/A/a/lib/country_manager.rb:88:in `country'
  /Users/raducroitoru/Coding/Work/A/a/app/models/api/v5/search_criteria_adapter.rb:57:in `country_locale'
  /Users/raducroitoru/Coding/Work/A/a/app/models/api/v5/search_criteria_adapter.rb:11:in `criteria'  
```

**spec_helper.rb**

```ruby
require 'rubygems'

ENV["RAILS_ENV"] ||= 'test'

require File.expand_path("../../config/environment", __FILE__)
require 'knapsack'
require 'rspec/rails'
require 'email_spec'
require 'vcr'
require 'sidekiq/testing'
require "fakeredis/rspec"
require 'webmock/rspec'
require 'paper_trail/frameworks/rspec'
require 'shoulda/matchers'

# Requires supporting ruby files with custom matchers and macros, etc,
# in spec/support/ and its subdirectories.
Dir[Rails.root.join("spec/support/**/*.rb")].each {|f| require f}

Knapsack::Adapters::RSpecAdapter.bind

Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    with.test_framework :rspec
    with.library :rails
  end
end

RSpec.configure do |config|
  puts "################## Rspec configure"

  config.infer_spec_type_from_file_location!
  config.mock_with :rspec
  config.use_transactional_fixtures = false
  config.include RequestHelpers
  config.include EmailSpec::Helpers
  config.include EmailSpec::Matchers
  config.include CountryHelper
  config.extend WithModel

  # For using focus tags
  config.filter_run :focus => true
  config.run_all_when_everything_filtered = true
  config.tty = true

  config.before :each do
    puts "################## Before each: setting country"

    CountryManager.country = :da
  end

  config.after :each, except: 'zipcode de' do
    puts "################## After each"

    # TODO Sanity stabilization experiment (2015-01, remove again soon)
    expect(CountryManager.country).to eq(:da)
  end
end
```

Knapsack: 1.13.2
Rbenv with ruby 2.4.0
Rails: 4.2.8
Rspec: 3.5.0
Rspec-rails: 3.5.2

It's working fine with normal rspec command. Is this supported?

**Comment by ArturT** [comment]
Maybe try this but it seems the spec_helper.rb is already loaded. You can provide other options to play with rspec configuration.

```
knapsack rspec "--require spec_helper.rb"
```

or try load rspec via bundler
```
bundle exec rake knapsack:rspec
```

or this, maybe the order does matter and your knapsack report json ended up in a specific order that gives you the order depended bug and some of your code removes the country.
```
knapsack rspec "--order rand"
```

Please try to follow backtrace to find root problem, if it's in particular spec file or somewhere else.

**Comment by radubogdan** [comment]
Hey @ArturT 

The only command with a different output is `bundle exec rake knapsack:rspec`

```
bundler: failed to load command: rspec (/Users/raducroitoru/.rbenv/versions/2.4.0/bin/rspec)
LoadError: cannot load such file -- rspec/rails
  /Users/raducroitoru/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
  /Users/raducroitoru/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
  /Users/raducroitoru/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
  /Users/raducroitoru/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
  /Users/raducroitoru/Coding/Work/X/x/spec/spec_helper.rb:5:in `<top (required)>'
  /Users/raducroitoru/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /Users/raducroitoru/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /Users/raducroitoru/Coding/Work/X/x/spec/mailers/user_mailer_spec.rb:1:in `<top (required)>'
  /Users/raducroitoru/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load'
  /Users/raducroitoru/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
  /Users/raducroitoru/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `each'
  /Users/raducroitoru/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
  /Users/raducroitoru/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:100:in `setup'
  /Users/raducroitoru/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
  /Users/raducroitoru/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
  /Users/raducroitoru/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
  /Users/raducroitoru/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'
  /Users/raducroitoru/.rbenv/versions/2.4.0/bin/rspec:22:in `load'
  /Users/raducroitoru/.rbenv/versions/2.4.0/bin/rspec:22:in `<top (required)>'
```

The other two outputs the same error. I can't figure out what's the root problem. Everything works if I invoke rspec normally (`bundle exec rspec spec`)

**Comment by ArturT** [comment]
Do you have .rspec file and what is the content?

Do you require spec_helper.rb or rails_helper.rb in your spec files?

Maybe try this:

```
bundle exec rake "knapsack:rspec[--require spec/spec_helper.rb]"
# or this
bundle exec rake "knapsack:rspec[--require spec/rails_helper.rb]"
```

Or maybe this error is related to binstubs https://github.com/ArturT/knapsack/issues/54

**Comment by ArturT** [comment]
Please update knapsack to 1.13.3 just to ensure it's not related to https://github.com/ArturT/knapsack/issues/57

**Comment by radubogdan** [comment]
1. I have a `.rspec` 

```
--color
--format Fuubar
--order random
``` 

2. I don't have a `rails_helper.rb` file. I require `spec_helper.rb` in every spec.
3. I saw #54 before I opened this issue, but it doesn't seem related to my problem. I tried synth's fork but still doesn't work.
4. I've updated to 1.13.3 but it still fails with the country error and your last command fails with `LoadError: cannot load such file -- rspec/rails`.

**Comment by ArturT** [comment]
Maybe try to `require 'knapsack'` right before `Knapsack::Adapters::RSpecAdapter.bind`.

How you Gemfile looks like?

You could try https://github.com/KnapsackPro/knapsack_pro-ruby and see if it fails too. The RSpec is loaded differently there. Maybe it will work instead of knapsack.

**Comment by radubogdan** [comment]
Relevant part:

```
group :development, :test, :staging do
  gem 'teaspoon-jasmine'
  gem 'poltergeist'

  gem 'knapsack', '~> 1.13.3'

  gem 'brakeman'
end
```

KnapsackPro gived me the same Country error.

I did a rails dummy app (same ruby/rails/rspec/knapsack versions) which configures the exact same before each block inside Rspec.configure and wrote some mock tests. Looks like it's working and the problem is related to my repo. I'll try to extensively debug this in the weekend and come back if I find the problem.

Thanks for your input @ArturT

**Comment by radubogdan** [comment]
Ok the problem was that I was invoking something in a spec who required the setting of the country and because this was not happening inside a `it` block the `before(:each)` for `Rspec.configure` was not called.

Example:

```
describe "#self.criteria" do
    CM.c = :da <----- THIS WAS MY CHANGE
    Api::V6::SearchCriteriaAdapter.criteria.each do |crit|  <------- This is using country and because it's inside describe and not it, the callback from spec_helper.rb is not run.
       ........................................
       ........................................
    end
end
```
